name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    name: Clojure
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prepare java
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 111

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: latest
    - name: Cache clojure dependencies
      uses: actions/cache@v4.2.4
      with:
        path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
            .cpcache
          # List all files containing dependencies:
        key: cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: cljdeps-
    - name: Start clojure tests
      run: clojure -M:clj-test
    - name: Start clojurescript tests
      run: clojure -M:cljs-test

